name: Windows Cloud PC - AnyDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Windows PC
    runs-on: windows-latest
    timeout-minutes: 4320

    steps:
      - name: Baixar e Instalar Tudo
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/7eiczvgil84czu55dxep3/Downloads.bat?rlkey=wzdc1wxjsph2b7r0atplmdz3p&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Iniciar AnyDesk
        run: |
          if (Test-Path "start.bat") {
            cmd /c start.bat
          } else {
            Write-Host "ERRO: start.bat não encontrado!"
          }

      - name: Manter o PC Ligado
        run: |
          Write-Host "✅ PC está rodando! Olhe os logs abaixo para pegar o ID do AnyDesk"
          Start-Sleep -Seconds 259200
